USE [master]
GO
/****** Object:  Database [Drivers]    Script Date: 18.04.2022 15:14:30 ******/
CREATE DATABASE [Drivers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Drivers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Drivers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Drivers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Drivers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Drivers] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Drivers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Drivers] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Drivers] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Drivers] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Drivers] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Drivers] SET ARITHABORT OFF 
GO
ALTER DATABASE [Drivers] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Drivers] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Drivers] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Drivers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Drivers] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Drivers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Drivers] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Drivers] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Drivers] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Drivers] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Drivers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Drivers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Drivers] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Drivers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Drivers] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Drivers] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Drivers] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Drivers] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Drivers] SET  MULTI_USER 
GO
ALTER DATABASE [Drivers] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Drivers] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Drivers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Drivers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Drivers] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Drivers] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Drivers] SET QUERY_STORE = OFF
GO
USE [Drivers]
GO
/****** Object:  Table [dbo].[Drivers]    Script Date: 18.04.2022 15:14:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Drivers](
	[Идентификатор (GUID)] [int] NOT NULL,
	[Фамилия] [nvarchar](50) NULL,
	[Имя] [nvarchar](50) NULL,
	[Отчество] [nvarchar](50) NULL,
	[Пасспорт (серия и номер)] [nvarchar](50) NULL,
	[Адрес регистрации] [nvarchar](50) NULL,
	[Адрес проживания] [nvarchar](50) NULL,
	[Место работы] [nvarchar](50) NULL,
	[Должность] [nvarchar](50) NOT NULL,
	[Мобильный телефон] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Фотография] [nvarchar](50) NULL,
	[Замечания] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Drivers] PRIMARY KEY CLUSTERED 
(
	[Идентификатор (GUID)] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (1, N'Hopkins', N'Alonso', N'Caleb', N'2303 160716', N'760832 452 Cobblestone St.', N'760832 452 Cobblestone St.', N'Global Gillette', N'Reporter', N'9703838933', N'skippy@icloud.com', N'001-happy-18.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (2, N'Sellers', N'Kaydence', N'Susannah', N'5563 160745', N'807042 Hyattsville, MD 20782', N'807042 Hyattsville, MD 20782', N'Coca-Cola', N'Elementary School Teacher', N'8677084447', N'isotopian@sbcglobal.net', N'002-cool-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (3, N'Bray', N'Finnegan', N'Brighton', N'3719 717453', N'83282 9648 Philmont Lane', N'83282 9648 Philmont Lane', N'Harley-Davidson Motor Company', N'Childcare worker', N'2214287850', N'isaacson@att.net', N'003-happy-17.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (4, N'Arias', N'Gideon', N'Varian', N'5810 721066', N'768289 Hanover Park, IL 60133', N'768289 Hanover Park, IL 60133', N'Corona', N'Loan Officer', N'7862747872', N'mugwump@mac.com', N'004-surprised-9.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (5, N'Schultz', N'Case', N'Aiden', N'2208 937197', N'780691 8438 North Fairground Court', N'780691 8438 North Fairground Court', N'Johnnie Walker', N'Drafter', N'3657526445', N'mcmillan@optonline.net', N'005-shocked-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (6, N'Alvarado', N'Pierre', N'Harriet', N'7184 275223', N'845839 Woodstock, GA 30188', N'845839 Woodstock, GA 30188', N'SAP', N'Cost Estimator', N'4466396043', N'dinther@hotmail.com', N'006-shocked-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (7, N'Bell', N'Esteban', N'Cameron', N'9563 574791', N'94009 148 Catherine Dr.', N'94009 148 Catherine Dr.', N'Smirnoff', N'Clinical Laboratory Technician', N'5554448316', N'pizza@yahoo.com', N'007-nervous-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (8, N'Anderson', N'Spencer', N'Meaghan', N'9008 379623', N'674783 Lithonia, GA 30038', N'674783 Lithonia, GA 30038', N'Toyota Motor Corporation', N'Electrician', N'3926824442', N'murty@outlook.com', N'008-nervous-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (9, N'Sweeney', N'Seth', N'Jax', N'3810 530169', N'845247 708 6th Drive', N'845247 708 6th Drive', N'Caterpillar Inc.', N'Referee', N'8364290386', N'aegreene@me.com', N'009-angry-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (10, N'Mason', N'Lincoln', N'Emeline', N'5387 689700', N'252988 Egg Harbor Township, NJ 08234', N'252988 Egg Harbor Township, NJ 08234', N'Avon', N'Judge', N'2839453092', N'jnolan@aol.com', N'010-drool.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (11, N'Curtis', N'Lindsay', N'Syllable', N'1152 481271', N'777867 8992 Union Rd.', N'777867 8992 Union Rd.', N'Budweiser Stag Brewing Company', N'Security Guard', N'6213593669', N'msherr@optonline.net', N'011-tired-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (13, N'Sellers', N'Darien', N'Nadeen', N'5110 869140', N'779085 12 Windsor St.', N'779085 12 Windsor St.', N'Chase', N'Painter', N'3319182434', N'punkis@hotmail.com', N'013-tongue-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (14, N'Schneider', N'Jaylene', N'Xavier', N'6948 84332', N'144573 Waynesboro, PA 17268', N'144573 Waynesboro, PA 17268', N'NTT Data', N'Occupational Therapist', N'9446270176', N'pereinar@yahoo.com', N'014-tongue-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (15, N'Schmitt', N'Leonard', N'Vincent', N'7045 366325', N'864380 549 Lake View Dr.', N'864380 549 Lake View Dr.', N'Intel Corporation', N'Physical Therapist', N'6214057195', N'tskirvin@mac.com', N'015-smile-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (16, N'Richardson', N'Maya', N'Heath', N'7100 947091', N'265294 Garland, TX 75043', N'265294 Garland, TX 75043', N'Sony', N'Photographer', N'8376391067', N'kewley@sbcglobal.net', N'016-sleeping-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (17, N'Delacruz', N'Thalia', N'Caprice', N'9169 340517', N'137788 314 N. Gulf Lane', N'137788 314 N. Gulf Lane', N'Tesco Corporation', N'Cashier', N'7696107084', N'ehood@icloud.com', N'017-nervous.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (18, N'Baird', N'Maci', N'Dustin', N'3097 188032', N'340075 Hollywood, FL 33020', N'340075 Hollywood, FL 33020', N'Microsoft', N'Educator', N'3086867622', N'ilial@aol.com', N'018-surprised-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (19, N'Stephenson', N'Ace', N'Amity', N'7796 170860', N'531408 3 Cooper Street', N'531408 3 Cooper Street', N'McDonald''s', N'Professional athlete', N'3198723287', N'elmer@comcast.net', N'019-tongue-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (20, N'Castro', N'Robert', N'Isaiah', N'5001 550223', N'912556 Coventry, RI 02816', N'912556 Coventry, RI 02816', N'VISA', N'Janitor', N'3416205356', N'scarolan@live.com', N'020-happy-16.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (21, N'Stark', N'Efrain', N'Jared', N'4204 741281', N'838795 53 E. Marvon St.', N'838795 53 E. Marvon St.', N'Zara', N'Massage Therapist', N'2665617456', N'bwcarty@yahoo.com', N'021-wink-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (22, N'Montgomery', N'Katelynn', N'Drake', N'1209 731500', N'520544 Jamaica Plain, MA 02130', N'520544 Jamaica Plain, MA 02130', N'Morgan Stanley', N'Psychologist', N'4086730059', N'facet@outlook.com', N'022-laughing-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (23, N'Freeman', N'Sammy', N'Lane', N'1085 749551', N'902946 15 Indian Summer St.', N'902946 15 Indian Summer St.', N'Mitsubishi', N'IT Manager', N'9068255704', N'metzzo@att.net', N'023-laughing-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (24, N'Stokes', N'Jamal', N'Rayleen', N'7125 277444', N'684826 Canton, GA 30114', N'684826 Canton, GA 30114', N'Audi', N'Anthropologist', N'8667324338', N'slaff@aol.com', N'024-sweat-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (25, N'Bell', N'Lilliana', N'Quintin', N'4858 465200', N'299125 1 Rockville Ave.', N'299125 1 Rockville Ave.', N'eBay', N'Executive Assistant', N'7448769856', N'caidaperl@mac.com', N'025-happy-15.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (26, N'Ali', N'Jaidyn', N'Kaitlin', N'9255 131955', N'623940 Piedmont, SC 29673', N'623940 Piedmont, SC 29673', N'Ralph Lauren Corporation', N'Artist', N'8722303310', N'jigsaw@verizon.net', N'026-happy-14.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (27, N'Nixon', N'Solomon', N'Jolee', N'3965 425455', N'243802 154 Galvin Ave.', N'243802 154 Galvin Ave.', N'Wal-Mart', N'Mechanical Engineer', N'5724672895', N'hoyer@optonline.net', N'027-laughing.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (28, N'Mcdowell', N'Isaias', N'Kalan', N'4368 409875', N'697427 Savannah, GA 31404', N'697427 Savannah, GA 31404', N'Panasonic Corporation', N'Firefighter', N'4517686075', N'danneng@msn.com', N'028-happy-13.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (29, N'Dean', N'Neveah', N'Evony', N'9283 299023', N'503601 56 Annadale Dr.', N'503601 56 Annadale Dr.', N'Nike, Inc.', N'Carpenter', N'5558026671', N'burniske@outlook.com', N'029-happy-12.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (30, N'Waters', N'Koen', N'Abraham', N'4065 664366', N'732787 Lititz, PA 17543', N'732787 Lititz, PA 17543', N'Nissan Motor Co., Ltd.', N'Actuary', N'8334605788', N'jipsen@sbcglobal.net', N'030-crying-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (31, N'Odom', N'Cale', N'Ann', N'4877 252066', N'650754 7285 Locust Drive', N'650754 7285 Locust Drive', N'MTV', N'Compliance Officer', N'2348958976', N'agapow@hotmail.com', N'031-crying-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (32, N'Ruiz', N'Layton', N'Aryn', N'8656 317830', N'924502 Jackson Heights, NY 11372', N'924502 Jackson Heights, NY 11372', N'Cartier SA', N'Computer Systems Administrator', N'6824698567', N'mobileip@icloud.com', N'032-bored.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (33, N'Patrick', N'Monserrat', N'Coralie', N'1583 513755', N'670778 935 West Ave.', N'670778 935 West Ave.', N'Nescafé', N'HR Specialist', N'6825557940', N'mglee@yahoo.com', N'033-cool-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (34, N'Hardin', N'Kamden', N'Ray', N'2179 517256', N'939472 Columbus, GA 31904', N'939472 Columbus, GA 31904', N'Allianz', N'Recreation & Fitness Worker', N'5759857625', N'animats@yahoo.ca', N'034-angry-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (36, N'Winters', N'Cornelius', N'James', N'9584 586486', N'424571 Maryville, TN 37803', N'424571 Maryville, TN 37803', N'Kleenex', N'Auto Mechanic', N'6087830267', N'slanglois@msn.com', N'036-angry-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (37, N'Love', N'Kaden', N'Neil', N'1850 453434', N'478037 139 N. Grand St.', N'478037 139 N. Grand St.', N'Tiffany & Co.', N'Web Developer', N'6886567203', N'notaprguy@verizon.net', N'037-happy-11.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (38, N'Mills', N'Finley', N'Ace', N'4286 976952', N'843098 Irwin, PA 15642', N'843098 Irwin, PA 15642', N'3M', N'Civil Engineer', N'5304027915', N'yruan@sbcglobal.net', N'038-angry-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (39, N'Henry', N'Markus', N'Edward', N'2767 784535', N'900432 400 Amerige St.', N'900432 400 Amerige St.', N'Shell Oil Company', N'Chemist', N'2626352834', N'bmorrow@me.com', N'039-cyclops-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (40, N'Singleton', N'Romeo', N'Preston', N'7677 990002', N'425361 Evans, GA 30809', N'425361 Evans, GA 30809', N'Adobe Systems', N'Recreational Therapist', N'4879573536', N'adillon@verizon.net', N'040-surprised-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (41, N'Glenn', N'Ethen', N'Kate', N'6342 37367', N'815003 225 Iroquois St.', N'815003 225 Iroquois St.', N'IKEA', N'Microbiologist', N'9182854740', N'kimvette@me.com', N'041-thinking-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (42, N'Gordon', N'Abbey', N'Berlynn', N'8909 475995', N'60302 Vienna, VA 22180', N'60302 Vienna, VA 22180', N'Nokia', N'Event Planner', N'4127068937', N'emcleod@outlook.com', N'042-book.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (43, N'Vasquez', N'Presley', N'Sheridan', N'9144 720543', N'529399 44 Ocean Ave.', N'529399 44 Ocean Ave.', N'Sprite', N'Coach', N'4543538089', N'stomv@aol.com', N'043-baby-boy.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (44, N'Levine', N'Alexis', N'Juan', N'6021 143882', N'191499 Long Beach, NY 11561', N'191499 Long Beach, NY 11561', N'Xerox', N'Radiologic Technologist', N'6237167237', N'msusa@comcast.net', N'044-dead-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (45, N'Miles', N'Steve', N'Lydon', N'4607 499410', N'292234 192 West Foster St.', N'292234 192 West Foster St.', N'Samsung Group', N'Market Research Analyst', N'5946158545', N'dougj@yahoo.com', N'045-star.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (46, N'Cuevas', N'Kayley', N'Tyson', N'4676 263545', N'194258 Long Branch, NJ 07740', N'194258 Long Branch, NJ 07740', N'Google', N'Housekeeper', N'6478852301', N'jlbaumga@gmail.com', N'046-dubious.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (47, N'Hebert', N'Annabelle', N'Annora', N'6571 27113', N'415905 43 SE. Cross Court', N'415905 43 SE. Cross Court', N'Louis Vuitton', N'Computer Programmer', N'8226933953', N'temmink@mac.com', N'047-phone-call.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (48, N'Casey', N'Carolina', N'Timothy', N'2307 511412', N'598986 Centereach, NY 11720', N'598986 Centereach, NY 11720', N'Apple Inc.', N'Secretary', N'8872368493', N'nighthawk@msn.com', N'048-moon.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (49, N'Roach', N'Beckham', N'Elias', N'4756 956293', N'906312 946 Yukon Lane', N'906312 946 Yukon Lane', N'Verizon Communications', N'Bus Driver', N'5315970196', N'qmacro@outlook.com', N'049-robot.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (50, N'Pugh', N'Seamus', N'Jackson', N'4693 133588', N'989757 Winter Springs, FL 32708', N'989757 Winter Springs, FL 32708', N'Credit Suisse', N'Systems Analyst', N'5067741574', N'stewwy@att.net', N'050-flower.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (51, N'Calderon', N'Imani', N'Sullivan', N'7598 90859', N'46335 330 Poplar Lane', N'46335 330 Poplar Lane', N'Wells Fargo', N'Chef', N'6398138035', N'blixem@msn.com', N'051-happy-10.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (52, N'Roach', N'Marisol', N'Dezi', N'2416 240325', N'245515 Titusville, FL 32780', N'245515 Titusville, FL 32780', N'Yahoo!', N'Registered Nurse', N'8834555204', N'mccurley@optonline.net', N'052-happy-9.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (53, N'Jacobson', N'Kane', N'Emerson', N'3896 957754', N'368276 626 Leatherwood St.', N'368276 626 Leatherwood St.', N'Porsche', N'Surveyor', N'8339144764', N'jacks@mac.com', N'053-tired-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (54, N'Higgins', N'Anya', N'Erin', N'6573 581276', N'372963 Lynn, MA 01902', N'372963 Lynn, MA 01902', N'Moët et Chandon', N'Urban Planner', N'8109453933', N'nwiger@att.net', N'054-ugly-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (55, N'Richard', N'Branson', N'Linnea', N'2225 886655', N'446339 9971 N. Rockville Avenue', N'446339 9971 N. Rockville Avenue', N'Hyundai', N'Middle School Teacher', N'9956109002', N'muadip@me.com', N'055-tongue-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (56, N'Mathis', N'Kyle', N'Raine', N'8966 340666', N'490162 Duluth, GA 30096', N'490162 Duluth, GA 30096', N'Honda Motor Company, Ltd', N'Speech-Language Pathologist', N'3945813937', N'gavinls@yahoo.com', N'056-vampire.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (57, N'Cross', N'Jamiya', N'Trevor', N'1754 958143', N'246531 9542 Sutor Drive', N'246531 9542 Sutor Drive', N'Beko', N'Personal Care Aide', N'7323752363', N'nicktrig@me.com', N'057-music-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (58, N'Keller', N'Selah', N'Merle', N'4434 406702', N'268770 Phoenixville, PA 19460', N'268770 Phoenixville, PA 19460', N'Deere & Company', N'Database administrator', N'5874442070', N'lbecchi@me.com', N'058-popcorn.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (59, N'Watson', N'Larry', N'Blayne', N'4859 211563', N'898596 299 E. George St.', N'898596 299 E. George St.', N'Volkswagen Group', N'Art Director', N'8454381802', N'willg@att.net', N'059-nurse.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (60, N'', N'Braeden .Shea', N'Abe', N'5348 104186', N'316595 Westport, CT 06880', N'316595 Westport, CT 06880', N'Pampers', N'Landscaper & Groundskeeper', N'3204783865', N'rnelson@yahoo.com', N'060-sad-13.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (61, N'', N'Allisson .Woodard', N'Joan', N'9216 132859', N'635754 7671 Tunnel Street', N'635754 7671 Tunnel Street', N'BlackBerry', N'Court Reporter', N'4868288733', N'roesch@aol.com', N'061-graduated-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (62, N'', N'Amy .Garner', N'Tanner', N'6127 199319', N'509105 Fair Lawn, NJ 07410', N'509105 Fair Lawn, NJ 07410', N'Jack Daniel''s', N'Bookkeeping clerk', N'4972158724', N'pthomsen@verizon.net', N'062-happy-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (63, N'', N'Saniyah .Choi', N'Debree', N'1102 719495', N'815229 41 Harvard Drive', N'815229 41 Harvard Drive', N'Facebook, Inc.', N'Landscape Architect', N'3998873591', N'itstatus@yahoo.ca', N'063-hungry.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (64, N'', N'Reagan .Simmons', N'Sharon', N'2020 814747', N'470174 Windsor, CT 06095', N'470174 Windsor, CT 06095', N'United Parcel Service', N'College Professor', N'2052784756', N'marcs@verizon.net', N'064-police.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (65, N'', N'Coby .Robertson', N'Juliet', N'4083 683928', N'133197 7219 Prospect Drive', N'133197 7219 Prospect Drive', N'Adidas', N'Respiratory Therapist', N'2608147458', N'tellis@yahoo.ca', N'065-crying-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (66, N'', N'Dakota .Haney', N'Marguerite', N'1270 718764', N'946776 Rolla, MO 65401', N'946776 Rolla, MO 65401', N'Siemens AG', N'Mason', N'3028443480', N'scotfl@att.net', N'066-happy-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (67, N'', N'Malia .Rivas', N'Louis', N'3871 532007', N'875661 697 Cypress Lane', N'875661 697 Cypress Lane', N'Citigroup', N'Veterinarian', N'4493807477', N'jramio@optonline.net', N'067-sun.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (68, N'', N'Lily .Green', N'Lynn', N'9827 633690', N'976908 Arlington Heights, IL 60004', N'976908 Arlington Heights, IL 60004', N'Amazon.com', N'Architect', N'2802148022', N'mastinfo@gmail.com', N'068-father-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (69, N'', N'Reilly .Nielsen', N'Marcella', N'9350 821275', N'836368 7762 North County St.', N'836368 7762 North County St.', N'AT&T', N'Accountant', N'9677636475', N'ateniese@outlook.com', N'069-happy-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (70, N'', N'Ryleigh .Brooks', N'Leonie', N'2681 769203', N'532086 Holly Springs, NC 27540', N'532086 Holly Springs, NC 27540', N'Starbucks', N'School Counselor', N'6258105235', N'ismail@hotmail.com', N'070-late.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (71, N'', N'Brendan .Ewing', N'Adele', N'4152 160995', N'626951 7773 Ridge Dr.', N'626951 7773 Ridge Dr.', N'Prada', N'Computer Support Specialist', N'79754835566', N'oechslin@optonline.net', N'071-heart.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (72, N'', N'Cheyenne .Kirk', N'Julian', N'4306 595389', N'40675 New Haven, CT 06511', N'40675 New Haven, CT 06511', N'Gap Inc.', N'Historian', N'77188502518', N'jugalator@att.net', N'072-sick-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (73, N'', N'Jacoby .Rojas', N'Rose', N'9367 402446', N'7428 551 Spruce St.', N'7428 551 Spruce St.', N'Kia Motors', N'Computer Hardware Engineer', N'75506452520', N'subir@verizon.net', N'073-sad-12.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (74, N'', N'Keshawn .Cummings', N'Paul', N'4536 115339', N'249425 Mount Holly, NJ 08060', N'249425 Mount Holly, NJ 08060', N'Cisco Systems, Inc.', N'Designer', N'75512704620', N'bryam@verizon.net', N'074-in-love-10.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (75, N'', N'Mohammed .Crawford', N'Amelia', N'8478 213639', N'327248 116 Woodside St.', N'327248 116 Woodside St.', N'Home Depot', N'Hairdresser', N'74894443438', N'jpflip@optonline.net', N'075-shocked-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (76, N'', N'Nancy .Bryan', N'Devon', N'1871 347268', N'990658 Bridgewater, NJ 08807', N'990658 Bridgewater, NJ 08807', N'Vodafone', N'Lawyer', N'74018621637', N'mgemmons@comcast.net', N'076-happy-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (77, N'', N'Maxwell .Lynn', N'Ellory', N'1567 431190', N'707963 9817 Manor St.', N'707963 9817 Manor St.', N'Hewlett-Packard', N'Real Estate Agent', N'75076254900', N'csilvers@icloud.com', N'077-shocked-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (78, N'', N'Zack .Khan', N'Gabriel', N'9952 372202', N'670847 West Des Moines, IA 50265', N'670847 West Des Moines, IA 50265', N'Hermès', N'Customer Service Representative', N'74585660054', N'karasik@msn.com', N'078-cool-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (79, N'', N'Selina .Walls', N'Ashten', N'8168 514525', N'434380 9 Prince Street', N'434380 9 Prince Street', N'Oracle Corporation', N'Fitness Trainer', N'79793466593', N'wetter@yahoo.ca', N'079-crying-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (80, N'', N'Jerry .Garner', N'Everett', N'8239 393741', N'255295 Brookline, MA 02446', N'255295 Brookline, MA 02446', N'Canon', N'Social Worker', N'73205479952', N'thassine@me.com', N'080-zombie.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (81, N'', N'Kaila .Carroll', N'Grey', N'2909 822374', N'535063 549 Marvon St.', N'535063 549 Marvon St.', N'KFC', N'Economist', N'74298091931', N'sassen@msn.com', N'081-pain.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (82, N'', N'Sean .Conway', N'Garrison', N'5367 598823', N'325417 Dundalk, MD 21222', N'325417 Dundalk, MD 21222', N'General Electric', N'Writer', N'74642859954', N'jandrese@yahoo.ca', N'082-cyclops.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (83, N'', N'Makaila .Cantu', N'Fernando', N'5298 472573', N'825989 1 Theatre Drive', N'825989 1 Theatre Drive', N'BMW', N'Logistician', N'77484614491', N'tmccarth@live.com', N'083-sweat.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (84, N'', N'Jacquelyn .Mccall', N'Sherleen', N'3605 373737', N'964951 Lumberton, NC 28358', N'964951 Lumberton, NC 28358', N'The Walt Disney Company', N'Environmental scientist', N'75789351637', N'gtewari@icloud.com', N'084-thief.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (85, N'', N'Milton .Swanson', N'Chase', N'8146 691253', N'765391 673 Hamilton Road', N'765391 673 Hamilton Road', N'American Express', N'Patrol Officer', N'79276524631', N'hampton@yahoo.com', N'085-sad-11.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (86, N'', N'Rodolfo .Lynn', N'Zion', N'7932 623470', N'852333 Farmingdale, NY 11735', N'852333 Farmingdale, NY 11735', N'Burberry', N'Plumber', N'75956156057', N'jesse@me.com', N'086-kiss-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (87, N'', N'Paula .Walls', N'Breean', N'7817 774559', N'929343 9662 Bay Ave.', N'929343 9662 Bay Ave.', N'Pizza Hut', N'Dancer', N'77512403137', N'jugalator@me.com', N'087-father-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (88, N'', N'Adison .Olson', N'Henry', N'4402 114286', N'550100 Hamburg, NY 14075', N'550100 Hamburg, NY 14075', N'H&M', N'Pharmacist', N'76269742035', N'bhima@sbcglobal.net', N'088-father.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (89, N'', N'Jacob .Haynes', N'Marcellus', N'2794 857949', N'735633 8604 Fairfield Ave.', N'735633 8604 Fairfield Ave.', N'Heineken Brewery', N'Truck Driver', N'72019791451', N'gommix@comcast.net', N'089-angel-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (90, N'', N'Corinne .Roberts', N'Suzan', N'7429 823005', N'329850 Wisconsin Rapids, WI 54494', N'329850 Wisconsin Rapids, WI 54494', N'PepsiCo', N'Medical Secretary', N'74932193942', N'symbolic@verizon.net', N'090-happy-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (91, N'', N'Aimee .Ewing', N'Lane', N'6306 285690', N'230064 56 Vale St.', N'230064 56 Vale St.', N'Bank of America', N'Diagnostic Medical Sonographer', N'74074855030', N'bruck@outlook.com', N'091-sad-10.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (92, N'', N'Alejandro .Cordova', N'Hollyn', N'9370 315564', N'249749 Mount Juliet, TN 37122', N'249749 Mount Juliet, TN 37122', N'Nintendo', N'High School Teacher', N'79194782497', N'jeteve@optonline.net', N'092-outrage-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (93, N'', N'Byron .Haynes', N'Bram', N'1685 42988', N'97229 9523 Linda Lane', N'97229 9523 Linda Lane', N'Johnson & Johnson', N'Marriage & Family Therapist', N'74828029580', N'jsnover@comcast.net', N'093-ugly-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (94, N'', N'Genevieve .Keith', N'David', N'5467 865823', N'316039 Tullahoma, TN 37388', N'316039 Tullahoma, TN 37388', N'HSBC', N'Editor', N'74559446449', N'hakim@comcast.net', N'094-ugly-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (95, N'', N'Dane .Obrien', N'Shane', N'9596 712362', N'813449 3 Ashley Ave.', N'813449 3 Ashley Ave.', N'Kellogg Company', N'Substance Abuse Counselor', N'77103882563', N'dexter@sbcglobal.net', N'095-scared.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (96, N'', N'Nayeli .Church', N'Kent', N'9527 410913', N'790714 Ann Arbor, MI 48103', N'790714 Ann Arbor, MI 48103', N'MasterCard', N'Public Relations Specialist', N'77594523846', N'jlbaumga@hotmail.com', N'096-tongue-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (97, N'', N'Ashtyn .Jimenez', N'Rhett', N'6760 404116', N'515537 9851 East Prince Street', N'515537 9851 East Prince Street', N'Gucci', N'Computer Systems Analyst', N'76878011332', N'djupedal@hotmail.com', N'097-sad-9.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (98, N'', N'Kimberly .Wilkerson', N'Carelyn', N'9484 965470', N'262017 Dothan, AL 36301', N'262017 Dothan, AL 36301', N'Mercedes-Benz', N'Preschool Teacher', N'76913363494', N'daveewart@verizon.net', N'098-nerd-9.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (99, N'', N'Tripp .Curtis', N'Apollo', N'6426 682782', N'201742 8329 North Greenview St.', N'201742 8329 North Greenview St.', N'L''Oréal', N'Dentist', N'74932743888', N'msherr@sbcglobal.net', N'099-greed-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (100, N'', N'Eleanor .Zavala', N'George', N'3709 656706', N'905558 Hartford, CT 06106', N'905558 Hartford, CT 06106', N'Global Gillette', N'Teacher Assistant', N'79834704528', N'crusader@sbcglobal.net', N'100-whistle.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (101, N'', N'Harper .Thomas', N'Jae', N'4948 205524', N'243277 215 Purple Finch Lane', N'243277 215 Purple Finch Lane', N'Coca-Cola', N'Musician', N'74369518996', N'mdielmann@sbcglobal.net', N'101-nerd-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (102, N'', N'Maximo .Stephenson', N'Dex', N'8134 605243', N'119462 Annapolis, MD 21401', N'119462 Annapolis, MD 21401', N'Harley-Davidson Motor Company', N'Paralegal', N'72108897840', N'ovprit@me.com', N'102-muted-4.png', N'')
GO
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (103, N'', N'Kiara .James', N'Jeremy', N'7133 997003', N'791278 63 53rd Ave.', N'791278 63 53rd Ave.', N'Corona', N'Software Developer', N'73904997403', N'calin@att.net', N'103-in-love-9.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (104, N'', N'Isabella .Fuller', N'Naomi', N'4021 304017', N'306011 Hagerstown, MD 21740', N'306011 Hagerstown, MD 21740', N'Johnnie Walker', N'Zoologist', N'78057218540', N'thowell@yahoo.ca', N'104-in-love-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (105, N'', N'Cynthia .Garrison', N'Matilda', N'3516 398883', N'21763 2 Greenrose Rd.', N'21763 2 Greenrose Rd.', N'SAP', N'Medical Assistant', N'75782205882', N'mpiotr@yahoo.com', N'105-kiss-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (106, N'', N'Donte .Flowers', N'Brock', N'8533 684076', N'494549 Maspeth, NY 11378', N'494549 Maspeth, NY 11378', N'Smirnoff', N'Desktop publisher', N'74156318358', N'bester@gmail.com', N'106-in-love-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (107, N'', N'Asia .Rivera', N'Carmden', N'1618 439727', N'262275 298 N. Hudson Court', N'262275 298 N. Hudson Court', N'Toyota Motor Corporation', N'Actor', N'79009030657', N'imightb@gmail.com', N'107-ugly.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (108, N'', N'Trace .Hahn', N'Clelia', N'2835 991998', N'464652 Howell, NJ 07731', N'464652 Howell, NJ 07731', N'Caterpillar Inc.', N'Sports Coach', N'78794426528', N'jschauma@icloud.com', N'108-nerd-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (109, N'', N'Mohammed .Farley', N'Levi', N'7748 504230', N'200443 3 Peg Shop St.', N'200443 3 Peg Shop St.', N'Avon', N'Dental Hygienist', N'76493744690', N'syrinx@gmail.com', N'109-nerd-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (110, N'', N'Nicholas .Velez', N'Dawn', N'4853 175687', N'971839 Bayonne, NJ 07002', N'971839 Bayonne, NJ 07002', N'Budweiser Stag Brewing Company', N'School Psychologist', N'74878715975', N'konit@aol.com', N'110-crying-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (111, N'', N'Jamir .Curtis', N'Tavian', N'3983 947212', N'30097 648 Hill Field St.', N'30097 648 Hill Field St.', N'IBM', N'Librarian', N'75035726773', N'wonderkid@hotmail.com', N'111-muted-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (112, N'', N'Cyrus .Rose', N'Jacklyn', N'7435 360206', N'655574 South Richmond Hill, NY 11419', N'655574 South Richmond Hill, NY 11419', N'Chase', N'Telemarketer', N'77097566389', N'pjacklam@verizon.net', N'112-nerd-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (113, N'', N'Dakota .Torres', N'Cash', N'4559 179023', N'592365 477 Oakland Street', N'592365 477 Oakland Street', N'NTT Data', N'Interpreter & Translator', N'79316527478', N'tokuhirom@live.com', N'113-kiss-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (114, N'', N'Matias .Valencia', N'Reagan', N'2102 137023', N'279901 Lynnwood, WA 98037', N'279901 Lynnwood, WA 98037', N'Intel Corporation', N'Food Scientist', N'75244497554', N'adillon@comcast.net', N'114-greed-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (115, N'', N'Rocco .Harding', N'Gwendolen', N'2018 304278', N'690136 4 Division Lane', N'690136 4 Division Lane', N'Sony', N'Marketing Manager', N'73478078932', N'bcevc@yahoo.ca', N'115-pirate-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (116, N'', N'Maya .Clark', N'Evelyn', N'4625 441301', N'224776 Champlin, MN 55316', N'224776 Champlin, MN 55316', N'Tesco Corporation', N'Insurance Agent', N'76756948839', N'crobles@me.com', N'116-music.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (117, N'Hays', N'Bryan', N'Wade', N'8451 370682', N'475381 8021 Shadow Brook Dr.', N'475381 8021 Shadow Brook Dr.', N'Microsoft', N'Farmer', N'77799668126', N'tjensen@verizon.net', N'117-confused-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (118, N'Nelson', N'Jessie', N'Jack', N'7035 527026', N'89070 Lancaster, NY 14086', N'89070 Lancaster, NY 14086', N'McDonald''s', N'Human Resources Assistant', N'77913574942', N'gozer@icloud.com', N'118-nerd-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (119, N'Franklin', N'Joy', N'Warren', N'2846 798890', N'15158 7073 Hall Avenue', N'15158 7073 Hall Avenue', N'VISA', N'Paramedic', N'72926627836', N'brbarret@yahoo.ca', N'119-greed.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (120, N'Lang', N'Carlie', N'Rebecca', N'9368 90494', N'983441 West Babylon, NY 11704', N'983441 West Babylon, NY 11704', N'Zara', N'Automotive mechanic', N'79523744396', N'mcnihil@me.com', N'120-nerd-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (121, N'Hurley', N'Issac', N'Blanche', N'7906 721186', N'930722 985B Winding Way Dr.', N'930722 985B Winding Way Dr.', N'Morgan Stanley', N'Receptionist', N'77588499991', N'damian@yahoo.com', N'121-crying-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (122, N'Sims', N'Ariel', N'Bailey', N'9254 479522', N'866890 South Windsor, CT 06074', N'866890 South Windsor, CT 06074', N'Mitsubishi', N'Construction Manager', N'75346872128', N'neonatus@aol.com', N'122-cheering.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (123, N'Delgado', N'Braedon', N'Oliver', N'3627 384983', N'821333 570 Old Bayberry Street', N'821333 570 Old Bayberry Street', N'Audi', N'Physician', N'76425484829', N'tellis@icloud.com', N'123-surprised-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (124, N'Suarez', N'Christian', N'Lee', N'5989 222522', N'74910 Billerica, MA 01821', N'74910 Billerica, MA 01821', N'eBay', N'Mathematician', N'79805315346', N'frode@live.com', N'124-muted-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (125, N'Marks', N'Lilah', N'Anthony', N'3584 358162', N'882011 9122 South Addison St.', N'882011 9122 South Addison St.', N'Ralph Lauren Corporation', N'Electrical Engineer', N'76283261104', N'sjava@aol.com', N'125-sick-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (126, N'Rowland', N'Jeffrey', N'Gillian', N'4406 46042', N'450845 East Lansing, MI 48823', N'450845 East Lansing, MI 48823', N'Wal-Mart', N'Physicist', N'76693357511', N'harryh@live.com', N'126-graduated.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (127, N'Jordan', N'Hannah', N'Verena', N'5511 931653', N'233625 14 West Fifth St.', N'233625 14 West Fifth St.', N'Panasonic Corporation', N'Police Officer', N'73993448840', N'elflord@me.com', N'127-angry-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (128, N'Hinton', N'Peyton', N'Benjamin', N'8020 284910', N'672826 Skokie, IL 60076', N'672826 Skokie, IL 60076', N'Nike, Inc.', N'Maintenance & Repair Worker', N'76436765328', N'ramollin@mac.com', N'128-in-love-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (129, N'Forbes', N'Clayton', N'Zachary', N'8660 236405', N'422773 7267 W. Roehampton St.', N'422773 7267 W. Roehampton St.', N'Nissan Motor Co., Ltd.', N'Statistician', N'75359837587', N'kronvold@mac.com', N'129-cool-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (130, N'Cabrera', N'Salvatore', N'Krystan', N'7218 277801', N'348484 Harrisonburg, VA 22801', N'348484 Harrisonburg, VA 22801', N'MTV', N'Epidemiologist', N'73109258844', N'louise@aol.com', N'130-confused-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (131, N'Taylor', N'Andre', N'Felix', N'4813 710684', N'233687 82 Oak Meadow Dr.', N'233687 82 Oak Meadow Dr.', N'Cartier SA', N'Reporter', N'74578476033', N'nanop@verizon.net', N'131-sad-8.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (132, N'Mcclain', N'Kadin', N'Riley', N'8704 683064', N'28020 Cambridge, MA 02138', N'28020 Cambridge, MA 02138', N'Nescafé', N'Elementary School Teacher', N'73307307648', N'gtewari@sbcglobal.net', N'132-nerd-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (133, N'Nichols', N'Jaida', N'Lucinda', N'9908 341967', N'683123 864 Highland Drive', N'683123 864 Highland Drive', N'Allianz', N'Childcare worker', N'76198834911', N'ylchang@mac.com', N'133-birthday-boy.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (134, N'Church', N'Reid', N'Candice', N'6752 159699', N'228468 Alliance, OH 44601', N'228468 Alliance, OH 44601', N'Ferrari S.p.A.', N'Loan Officer', N'74827447133', N'gommix@yahoo.com', N'134-surprised-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (135, N'Harrington', N'Karley', N'Kathryn', N'8059 911426', N'882058 9465 St Paul Avenue', N'882058 9465 St Paul Avenue', N'Kleenex', N'Drafter', N'73695374704', N'uncle@sbcglobal.net', N'135-selfie.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (136, N'Rivers', N'Beau', N'Lillian', N'8452 55461', N'577380 Massillon, OH 44646', N'577380 Massillon, OH 44646', N'Tiffany & Co.', N'Cost Estimator', N'75402398104', N'smcnabb@live.com', N'136-tongue-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (137, N'Bentley', N'Riley', N'Hugh', N'4452 331700', N'279775 7651 South La Sierra Dr.', N'279775 7651 South La Sierra Dr.', N'3M', N'Clinical Laboratory Technician', N'78637142111', N'shrapnull@aol.com', N'137-smart-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (138, N'Choi', N'Ellis', N'Julina', N'3520 765331', N'185983 Centreville, VA 20120', N'185983 Centreville, VA 20120', N'Shell Oil Company', N'Electrician', N'78396944168', N'djpig@sbcglobal.net', N'138-smart.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (139, N'Leon', N'Jaylyn', N'Ellison', N'8629 761047', N'629180 3 Alton Lane', N'629180 3 Alton Lane', N'Adobe Systems', N'Referee', N'79838686473', N'oechslin@hotmail.com', N'139-surprised-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (140, N'Mayer', N'Drew', N'Carlen', N'2381 911641', N'336638 Glen Allen, VA 23059', N'336638 Glen Allen, VA 23059', N'IKEA', N'Judge', N'73255747514', N'xnormal@verizon.net', N'140-3d-glasses.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (141, N'Walters', N'Ashleigh', N'Claude', N'3634 590673', N'418814 9441 W. Pineknoll Drive', N'418814 9441 W. Pineknoll Drive', N'Nokia', N'Security Guard', N'79216830258', N'atmarks@icloud.com', N'141-in-love-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (142, N'Dickerson', N'Scott', N'Arden', N'5913 725569', N'579121 Florence, SC 29501', N'579121 Florence, SC 29501', N'Sprite', N'Budget analyst', N'75034467180', N'makarow@comcast.net', N'142-sleeping.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (143, N'Knight', N'Kolton', N'Miriam', N'7702 344201', N'254837 7070 Shady Street', N'254837 7070 Shady Street', N'Xerox', N'Painter', N'74672435219', N'raides@yahoo.com', N'143-pirate.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (144, N'Boyle', N'Izabelle', N'Naveen', N'2262 625946', N'196936 Lewiston, ME 04240', N'196936 Lewiston, ME 04240', N'Samsung Group', N'Occupational Therapist', N'76337007724', N'hwestiii@mac.com', N'144-santa-claus.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (145, N'Singleton', N'Haylie', N'Sue', N'1646 243340', N'134470 146 East Bank Street', N'134470 146 East Bank Street', N'Google', N'Physical Therapist', N'76328747209', N'scitext@gmail.com', N'145-wink.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (146, N'Lin', N'Sariah', N'Olive', N'2153 460491', N'905724 Billings, MT 59101', N'905724 Billings, MT 59101', N'Louis Vuitton', N'Photographer', N'73685991877', N'gward@yahoo.ca', N'146-in-love-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (147, N'Spears', N'Chace', N'Elodie', N'3126 716773', N'124048 8723 Cedar Swamp Drive', N'124048 8723 Cedar Swamp Drive', N'Apple Inc.', N'Cashier', N'73248861499', N'bockelboy@outlook.com', N'147-tired.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (148, N'Frazier', N'Liam', N'Korin', N'8828 972758', N'885712 Norman, OK 73072', N'885712 Norman, OK 73072', N'Verizon Communications', N'Educator', N'73743564166', N'tubesteak@comcast.net', N'148-bang.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (149, N'Stokes', N'Joseph', N'William', N'8114 880420', N'561214 8419 E. Harvey Drive', N'561214 8419 E. Harvey Drive', N'Credit Suisse', N'Professional athlete', N'78689822419', N'krueger@mac.com', N'149-baby.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (150, N'Hurley', N'Lorelei', N'Coralie', N'8085 811955', N'969805 Groton, CT 06340', N'969805 Groton, CT 06340', N'Wells Fargo', N'Janitor', N'77817855837', N'skaufman@optonline.net', N'150-tongue.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (151, N'Leon', N'Miguel', N'Haiden', N'1318 208906', N'140377 179 Manchester St.', N'140377 179 Manchester St.', N'Yahoo!', N'Massage Therapist', N'489361-6374', N'tezbo@live.com', N'151-sick-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (152, N'Hamilton', N'Melina', N'Isaac', N'3115 642377', N'74940 Chelmsford, MA 01824', N'74940 Chelmsford, MA 01824', N'Porsche', N'Psychologist', N'872856-7001', N'crowl@icloud.com', N'152-outrage.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (153, N'Duke', N'Serena', N'Arthur', N'5150 553212', N'190255 70 Cambridge Ave.', N'190255 70 Cambridge Ave.', N'Moët et Chandon', N'IT Manager', N'812814-4854', N'plover@hotmail.com', N'153-injury.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (154, N'Dillon', N'Kristen', N'Kylie', N'4169 626192', N'521443 Durham, NC 27703', N'521443 Durham, NC 27703', N'Hyundai', N'Anthropologist', N'803510-4214', N'calin@aol.com', N'154-dead.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (155, N'Hawkins', N'Saniyah', N'Josiah', N'7466 33192', N'845900 566 S. Cherry Street', N'845900 566 S. Cherry Street', N'Honda Motor Company, Ltd', N'Executive Assistant', N'869369-9524', N'timtroyr@live.com', N'155-rich-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (156, N'Leach', N'Thalia', N'Nicolas', N'2646 768816', N'584534 Forney, TX 75126', N'584534 Forney, TX 75126', N'Beko', N'Artist', N'464585-3155', N'keutzer@yahoo.com', N'156-sick.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (157, N'Caldwell', N'Irene', N'Noah', N'5732 336554', N'660042 83 NE. Hill Dr.', N'660042 83 NE. Hill Dr.', N'Deere & Company', N'Mechanical Engineer', N'703958-7186', N'thurston@outlook.com', N'157-angel.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (158, N'Bowen', N'Nikhil', N'Glenn', N'5254 555116', N'207488 Norwood, MA 02062', N'207488 Norwood, MA 02062', N'Volkswagen Group', N'Firefighter', N'515615-0912', N'mbalazin@att.net', N'158-nerd-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (159, N'Charles', N'Jolie', N'Matteo', N'3285 403999', N'586366 556 Summerhouse Street', N'586366 556 Summerhouse Street', N'Pampers', N'Carpenter', N'854941-5210', N'dkasak@gmail.com', N'159-crying-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (160, N'Baxter', N'Xavier', N'Joseph', N'1373 588622', N'962553 Nottingham, MD 21236', N'962553 Nottingham, MD 21236', N'BlackBerry', N'Actuary', N'380573-4186', N'esbeck@comcast.net', N'160-crying-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (161, N'Dean', N'Lukas', N'Ellice', N'1890 691040', N'594473 9750 Hawthorne Ave.', N'594473 9750 Hawthorne Ave.', N'Jack Daniel''s', N'Compliance Officer', N'297369-0265', N'novanet@aol.com', N'161-muted-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (162, N'King', N'Athena', N'Lilibeth', N'3307 217825', N'236159 Muskogee, OK 74403', N'236159 Muskogee, OK 74403', N'Facebook, Inc.', N'Computer Systems Administrator', N'671293-5634', N'mhouston@me.com', N'162-surprised-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (163, N'Noble', N'Adan', N'Bree', N'3286 297169', N'238674 97 Elmwood Street', N'238674 97 Elmwood Street', N'United Parcel Service', N'HR Specialist', N'305214-6934', N'bahwi@yahoo.com', N'163-crying.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (164, N'Pham', N'Kiley', N'Madeleine', N'2401 289619', N'924581 Seymour, IN 47274', N'924581 Seymour, IN 47274', N'Adidas', N'Recreation & Fitness Worker', N'812919-9643', N'chrisj@outlook.com', N'164-sad-7.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (165, N'Johnston', N'Steven', N'Kai', N'8507 252786', N'812525 308 Studebaker Drive', N'812525 308 Studebaker Drive', N'Siemens AG', N'Financial Advisor', N'754769-3349', N'louise@gmail.com', N'165-cool-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (166, N'Hart', N'Ayana', N'Dash', N'9342 187671', N'123262 Algonquin, IL 60102', N'123262 Algonquin, IL 60102', N'Citigroup', N'Auto Mechanic', N'206323-2722', N'qrczak@me.com', N'166-happy-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (167, N'Copeland', N'Aileen', N'Seth', N'1067 401389', N'840534 15 Marsh St.', N'840534 15 Marsh St.', N'Amazon.com', N'Web Developer', N'273495-7160', N'arachne@hotmail.com', N'167-thinking-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (168, N'Pitts', N'Emery', N'Eli', N'2273 445653', N'327317 Garden City, NY 11530', N'327317 Garden City, NY 11530', N'AT&T', N'Civil Engineer', N'463932-3808', N'mfburgo@icloud.com', N'168-muted.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (169, N'Chavez', N'Vicente', N'Bernice', N'6403 754163', N'917835 8614 Charles Street', N'917835 8614 Charles Street', N'Starbucks', N'Chemist', N'551789-0645', N'karasik@att.net', N'169-confused.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (170, N'Monroe', N'Cherish', N'Vanessa', N'3912 930948', N'254859 Wake Forest, NC 27587', N'254859 Wake Forest, NC 27587', N'Prada', N'Recreational Therapist', N'574759-7866', N'hauma@icloud.com', N'170-happy-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (171, N'Petersen', N'Karley', N'Rory', N'4008 604291', N'450994 57 Gulf Avenue', N'450994 57 Gulf Avenue', N'Gap Inc.', N'Microbiologist', N'852802-5653', N'scitext@me.com', N'171-thinking.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (172, N'Le', N'Alondra', N'Clark', N'3059 930219', N'301844 South Lyon, MI 48178', N'301844 South Lyon, MI 48178', N'Kia Motors', N'Event Planner', N'342453-0606', N'matthijs@live.com', N'172-nerd.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (173, N'Bird', N'Dorian', N'Judd', N'5208 664172', N'833457 694 Linden St.', N'833457 694 Linden St.', N'Cisco Systems, Inc.', N'Coach', N'434574-4540', N'bryam@icloud.com', N'173-in-love-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (174, N'Goodwin', N'Karley', N'Noel', N'6338 777372', N'522008 Missoula, MT 59801', N'522008 Missoula, MT 59801', N'Home Depot', N'Radiologic Technologist', N'425783-2253', N'tellis@att.net', N'174-hypnotized.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (175, N'Davidson', N'Killian', N'Janetta', N'8029 73589', N'357874 8440 Lyme St.', N'357874 8440 Lyme St.', N'Vodafone', N'Market Research Analyst', N'889449-4391', N'makarow@verizon.net', N'175-cool.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (176, N'Melton', N'Ava', N'Annabel', N'1788 509266', N'809566 Zeeland, MI 49464', N'809566 Zeeland, MI 49464', N'Hewlett-Packard', N'Housekeeper', N'825301-8250', N'citadel@msn.com', N'176-shocked.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (177, N'Horton', N'Adam', N'Blake', N'2735 502335', N'933854 7632 Oakwood Rd.', N'933854 7632 Oakwood Rd.', N'Hermès', N'Computer Programmer', N'397334-2086', N'jaxweb@me.com', N'177-easter.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (178, N'Singh', N'Jaydin', N'Jordon', N'7540 934686', N'651032 Pembroke Pines, FL 33028', N'651032 Pembroke Pines, FL 33028', N'Oracle Corporation', N'Secretary', N'241570-3040', N'mcsporran@aol.com', N'178-surprised-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (179, N'Mckinney', N'Lexie', N'Charles', N'9803 515191', N'938289 881 Temple St.', N'938289 881 Temple St.', N'Canon', N'Bus Driver', N'713462-8265', N'tubesteak@mac.com', N'179-surprised-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (180, N'Calderon', N'Niko', N'Troy', N'7220 353462', N'163048 South El Monte, CA 91733', N'163048 South El Monte, CA 91733', N'KFC', N'Systems Analyst', N'854822-2331', N'kludge@verizon.net', N'180-surprised.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (181, N'Acevedo', N'Terrence', N'Viola', N'9575 262338', N'906781 9591 Honey Creek St.', N'906781 9591 Honey Creek St.', N'General Electric', N'Chef', N'439713-6117', N'lahvak@hotmail.com', N'181-furious.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (182, N'May', N'Madisyn', N'Byron', N'7751 986773', N'13897 Webster, NY 14580', N'13897 Webster, NY 14580', N'BMW', N'Registered Nurse', N'230906-8815', N'raides@sbcglobal.net', N'182-sad-6.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (183, N'Ponce', N'Jadon', N'Doran', N'9853 763831', N'457951 7018 Pilgrim Street', N'457951 7018 Pilgrim Street', N'The Walt Disney Company', N'Surveyor', N'598895-2899', N'gfxguy@aol.com', N'183-sad-5.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (184, N'Thornton', N'Jaylen', N'Tobias', N'2868 392150', N'998746 Bismarck, ND 58501', N'998746 Bismarck, ND 58501', N'American Express', N'Urban Planner', N'429678-1872', N'krueger@msn.com', N'184-sad-4.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (185, N'Kelly', N'Brendan', N'Damien', N'7019 883500', N'537973 697 Westminster St.', N'537973 697 Westminster St.', N'Burberry', N'Middle School Teacher', N'276750-1655', N'shang@yahoo.ca', N'185-sad-3.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (186, N'Houston', N'Helena', N'Murphy', N'1529 516117', N'374799 Harleysville, PA 19438', N'374799 Harleysville, PA 19438', N'Pizza Hut', N'Speech-Language Pathologist', N'805953-2020', N'kalpol@comcast.net', N'186-angry-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (187, N'Moon', N'Madalyn', N'Carleen', N'7513 42100', N'519988 959 Birchpond St.', N'519988 959 Birchpond St.', N'H&M', N'Personal Care Aide', N'611670-2147', N'kildjean@msn.com', N'187-rich.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (188, N'Johns', N'Marcelo', N'Louisa', N'5292 664723', N'936784 Euless, TX 76039', N'936784 Euless, TX 76039', N'Heineken Brewery', N'Database administrator', N'242487-7082', N'treeves@comcast.net', N'188-sad-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (189, N'Campos', N'Jay', N'Georgina', N'1446 216584', N'901170 67 Pumpkin Hill Lane', N'901170 67 Pumpkin Hill Lane', N'PepsiCo', N'Database administrator', N'939641-7992', N'timtroyr@icloud.com', N'189-happy-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (190, N'Sullivan', N'Khalil', N'Rylie', N'6353 693874', N'525378 Yorktown Heights, NY 10598', N'525378 Yorktown Heights, NY 10598', N'Bank of America', N'Landscaper & Groundskeeper', N'669482-2353', N'world@att.net', N'190-sad-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (191, N'Merritt', N'Nikhil', N'Claudia', N'8638 615943', N'809450 5 NE. Newcastle Drive', N'809450 5 NE. Newcastle Drive', N'Nintendo', N'Court Reporter', N'801814-0510', N'kspiteri@icloud.com', N'191-sad.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (192, N'Melendez', N'Blaine', N'Vivian', N'5428 298274', N'921280 Ithaca, NY 14850', N'921280 Ithaca, NY 14850', N'Johnson & Johnson', N'Bookkeeping clerk', N'362338-4199', N'rtanter@att.net', N'192-smile.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (193, N'Munoz', N'Clayton', N'Caylen', N'8862 885055', N'225076 94 Longbranch St.', N'225076 94 Longbranch St.', N'HSBC', N'Landscape Architect', N'897655-0021', N'twoflower@mac.com', N'193-in-love-2.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (194, N'Montgomery', N'Khalil', N'Eloise', N'2574 326715', N'276634 Mount Prospect, IL 60056', N'276634 Mount Prospect, IL 60056', N'Kellogg Company', N'College Professor', N'710859-3522', N'howler@msn.com', N'194-happy.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (195, N'Medina', N'Bruce', N'Elein', N'7843 990305', N'242952 566 Gulf St.', N'242952 566 Gulf St.', N'MasterCard', N'Respiratory Therapist', N'612934-2623', N'yfreund@sbcglobal.net', N'195-kiss-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (196, N'Landry', N'Lesly', N'Gregory', N'5688 765287', N'140550 Wantagh, NY 11793', N'140550 Wantagh, NY 11793', N'Gucci', N'Mason', N'896396-9500', N'nogin@msn.com', N'196-in-love-1.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (197, N'Hartman', N'Alyson', N'Lee', N'7217 461000', N'925983 518 Clinton Ave.', N'925983 518 Clinton Ave.', N'Mercedes-Benz', N'Veterinarian', N'533891-1018', N'onestab@live.com', N'197-in-love.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (198, N'Contreras', N'Ellen', N'Fawn', N'1559 96165', N'783035 Encino, CA 91316', N'783035 Encino, CA 91316', N'L''Oréal', N'Architect', N'309279-3798', N'lcheng@mac.com', N'198-kiss.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (199, N'Barr', N'Sofia', N'Kingston', N'3480 736537', N'897782 370 Ashley Lane', N'897782 370 Ashley Lane', N'KFC', N'Accountant', N'483664-9876', N'bdthomas@yahoo.com', N'199-angry.png', N'')
INSERT [dbo].[Drivers] ([Идентификатор (GUID)], [Фамилия], [Имя], [Отчество], [Пасспорт (серия и номер)], [Адрес регистрации], [Адрес проживания], [Место работы], [Должность], [Мобильный телефон], [Email], [Фотография], [Замечания]) VALUES (200, N'Wilkerson', N'Joyce', N'Payten', N'6440 241468', N'838036 Wausau, WI 54401', N'838036 Wausau, WI 54401', N'General Electric', N'School Counselor', N'765461-9730', N'hoangle@optonline.net', N'200-sleepy.png', N'')
GO
USE [master]
GO
ALTER DATABASE [Drivers] SET  READ_WRITE 
GO